/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/create-exam` | `/create-exam`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/create-homework` | `/create-homework`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `/exam/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/classes` | `/classes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/create-exam` | `/create-exam`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/create-homework` | `/create-homework`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/statistics` | `/statistics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(teacher)'}/exams` | `/exams`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exams${`?${string}` | `#${string}` | ''}` | `/exams${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/results${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/classes${`?${string}` | `#${string}` | ''}` | `/classes${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/create-exam${`?${string}` | `#${string}` | ''}` | `/create-exam${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/create-homework${`?${string}` | `#${string}` | ''}` | `/create-homework${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/statistics${`?${string}` | `#${string}` | ''}` | `/statistics${`?${string}` | `#${string}` | ''}` | `${'/(teacher)'}/exams${`?${string}` | `#${string}` | ''}` | `/exams${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/classes` | `/classes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/create-exam` | `/create-exam`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/create-homework` | `/create-homework`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/statistics` | `/statistics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(teacher)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | `/exam/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/exam/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
